name: demnistify-environment
channels:
  - defaults
  - pytorch
  - nvidia # If you want nvidia hardware acceleration
dependencies:
  # languages
  - python=3.10
  #- r # Do we like R more than python?

  # Data Dependencies
  - pandas

  # Learning Dependencies
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8 # If you own a CUDA enabled device
